sopt-makers/sopt.org-frontend

src/components/Header/DesktopHeader.tsx
src/hooks/useNoScroll.ts
src/lib/project.ts
src/views/ProjectPage/components/DesktopFilter.tsx
src/views/ProjectPage/components/ProjectCard.tsx
src/views/ProjectPage/components/ProjectEnrollSection.tsx
src/views/ProjectPage/components/ProjectList.tsx
src/views/ProjectPage/components/index.ts
src/views/ProjectPage/styles/desktop-filter.module.scss
src/views/ProjectPage/styles/project-enroll.module.scss
src/views/ProjectPage/styles/project-list.module.scss
src/views/ProjectPage/styles/project.module.scss
src/views/ProjectPage/types.ts

- 프로젝트 리스트 뷰 마크업 수정
- API Base URL 요약

Feat project list view

---

src/utils/dateFormat.ts
src/views/ProjectDetailPage/ProjectDetail.style.tsx
src/views/ProjectDetailPage/ProjectDetailPage.tsx
src/views/ProjectDetailPage/components/UpButton.tsx
src/views/ProjectDetailPage/types.ts
src/views/ProjectDetailPage/utils/getLinkNameAndSrcWithType.ts

[FEAT] API 변경사항 반영 및 break point 변경에 따른 UI 수정

---

src/components/Header/Header.tsx
src/views/ProjectDetailPage/ProjectDetail.style.tsx
src/views/ProjectDetailPage/ProjectDetailPage.tsx

[FEAT] QA 반영

---

.github/workflows/ci.yml
src/assets/icons/arrow-right-16x16.svg
src/components/Footer/Footer.style.tsx
src/components/Footer/Footer.tsx
src/components/Header/DesktopHeader.tsx
src/lib/project.ts
src/views/ProjectPage/ProjectPage.tsx
src/views/ProjectPage/components/common/EmptyContent.tsx
src/views/ProjectPage/components/filter/MobileFilterModal.tsx
src/views/ProjectPage/components/project/ProjectList.tsx
src/views/ProjectPage/components/project/project-list.module.scss
src/views/ProjectPage/lib/constants.ts

- 기획 QA 반영
- 디자인 QA 반영
- API URL env로 분리
- lint 수행하도록 CI 구축

Fix plan design qa

---

src/components/About/Seminar/PartInfos/PartInfos.tsx
src/components/History/HistoryList/HistoryList.tsx
src/components/Home/Introduce/IconBanner/IconBanner.tsx
src/components/Partners/Partners/PartnerCard/PartnerCard.tsx
src/components/Partners/Partners/Partners.tsx
src/components/Partners/Projects/Projects.tsx
src/lib/api.ts

변경된 API 반영

---

src/components/Header/MobileHeader/HeaderMenu.tsx
src/components/Header/MobileHeader/MobileHeader.tsx
src/views/ProjectPage/components/project/ProjectCard.tsx
src/views/ProjectPage/components/project/project-list.module.scss

feat: Design QA Header, Footer 반영

---

src/components/Header/MobileHeader/MobileHeader.tsx
src/views/ProjectDetailPage/ProjectDetail.style.tsx

chore/#41: 헤더 배경 색깔 안 맞는 이슈 수정

---

src/views/ProjectDetailPage/ProjectDetailPage.tsx

feat/#46: serviceType 웹,앱 이슈 수정

---

src/components/common/ScrollToTopButton/ScrollToTopButton.tsx
src/components/common/ScrollToTopButton/index.ts
src/components/index.ts
src/views/MainPage/MainPage.tsx
src/views/MainPage/assets/arrow-down.svg
src/views/MainPage/assets/arrow-left-28x28.svg
src/views/MainPage/assets/arrow-left.svg
src/views/MainPage/assets/arrow-right-28x28.svg
src/views/MainPage/components/ActivityDescription/ActivityDescription.tsx
src/views/MainPage/components/ActivityDescription/activity-description.module.scss
src/views/MainPage/components/BannerImage/BannerImage.tsx
src/views/MainPage/components/BannerImage/banner-image.module.scss
src/views/MainPage/components/CorporateLinkedActivities/CorporateLinkedActivities.tsx
src/views/MainPage/components/CorporateLinkedActivities/corporate-linked-activities.module.scss
src/views/MainPage/components/CorporatePartner/CorporatePartner.tsx
src/views/MainPage/components/CorporatePartner/corporate-partner.module.scss
src/views/MainPage/components/DetailedInformation/detailed-information.module.scss
src/views/MainPage/components/PartDescription/PartDescription.tsx
src/views/MainPage/components/PartDescription/part-description.module.scss
src/views/MainPage/components/SoptHistory/sopt-history.module.scss
src/views/MainPage/lib/index.ts
src/views/MainPage/lib/useHorizontalScroll.ts
src/views/MainPage/main-page.module.scss
src/views/ProjectDetailPage/components/UpButton.tsx

Feat main page desktop design guide

---

src/views/MainPage/components/CorporateLinkedActivities/CorporateLinkedActivities.tsx
src/views/MainPage/components/CorporateLinkedActivities/corporate-linked-activities.module.scss

fix: corporate linked activities 제목 왼쪽맞춤 적용

---

src/components/Header/Desktop/DesktopHeader.tsx
src/views/ProjectDetailPage/ProjectDetail.style.tsx
src/views/ProjectDetailPage/ProjectDetailPage.tsx

- detail page container 엘리먼트 생성
- 기존 min-height 속성 제거 및 margin 속성을 padding으로 대체

Project Detail Page 상단부 UI 깨짐현상 해결

---

src/hooks/useDevice.ts
src/pages/_app.tsx
src/views/FAQPage/FAQPage.tsx
src/views/FAQPage/components/contact/ContactInfo.tsx
src/views/FAQPage/components/contact/index.tsx
src/views/FAQPage/components/faq/QuestionBox.tsx
src/views/FAQPage/components/faq/index.tsx

- FAQ 페이지 질의응답 List 데이터 안보이는 이슈 해결 > 브레이크 포인트 문제였음

fix: 문의하기 페이지 깨짐 해결

---

src/hooks/useDevice.ts
src/pages/_app.tsx
src/views/FAQPage/FAQPage.tsx
src/views/FAQPage/components/contact/ContactInfo.tsx
src/views/FAQPage/components/contact/index.tsx
src/views/FAQPage/components/faq/QuestionBox.tsx
src/views/FAQPage/components/faq/index.tsx

Merge develop into main

---

src/components/Header/Desktop/DesktopHeader.tsx
src/components/Header/Header.tsx
src/components/common/ScrollToTopButton/scroll-to-top-button.module.scss
src/views/MainPage/MainPage.tsx
src/views/MainPage/components/ActivityDescription/ActivityDescription.tsx
src/views/MainPage/components/ActivityDescription/activity-description.module.scss
src/views/MainPage/components/BannerImage/banner-image.module.scss
src/views/MainPage/components/CorporateLinkedActivities/corporate-linked-activities.module.scss
src/views/MainPage/components/CorporatePartner/corporate-partner.module.scss
src/views/MainPage/components/DetailedInformation/detailed-information.module.scss
src/views/MainPage/components/PartDescription/PartDescription.tsx
src/views/MainPage/components/PartDescription/part-description.module.scss
src/views/MainPage/components/SoptHistory/sopt-history.module.scss
src/views/MainPage/main-page.module.scss
src/views/MainPage/stylesheets/_mixins.scss
src/views/MainPage/stylesheets/_variables.scss

- 메인페이지의  breakpoint 수정
기존 desktop breakpoint : 1920px
변경 desktop breakpoint : 1300px
- 헤더의 breakpoint 수정 
기존 desktop breakpoint : 1920px
변경 desktop breakpoint : 992px
- 메인 페이지 모든 컴포넌트의 Desktop 스타일 수정

메인페이지 Desktop 스타일 수정

---

src/views/MainPage/components/BannerImage/banner-image.module.scss
src/views/MainPage/components/CorporateLinkedActivities/corporate-linked-activities.module.scss
src/views/MainPage/main-page.module.scss

- 메인 페이지 내 컴포넌트 간 gap 수정
- 클릭 가능한 화살표에 대한 cursor: pointer 속성 추가

메인 페이지 내 컴포넌트간 gap을 포함한 스타일 수정

---

src/components/Header/Desktop/DesktopHeader.tsx
src/components/Header/Mobile/HeaderMenu.tsx

리크루팅 url 수정

---

src/components/common/CommonError/CommonError.tsx
src/components/common/RoundButton/RoundButton.tsx
src/utils/history.ts

lint 경고들을 제거합니다.
* any 사용
* missing dependency in useEffect

lint 워닝 제거

---

src/components/Footer/Channels/Channels.style.tsx
src/components/Footer/Channels/Channels.tsx
src/views/FAQPage/components/contact/ContactInfo.tsx
src/views/FAQPage/components/faq/QuestionBox.tsx
src/views/MainPage/components/ActivityDescription/activity-description.module.scss
src/views/MainPage/components/DetailedInformation/detailed-information.module.scss
src/views/MainPage/components/PartDescription/part-description.module.scss

클릭 가능한 엘리먼트는 호버하면 커서 모양이 바뀌면 사용자들이 보기에 좋습니다 !!
코드에 달아두겠습니다!
천천히 보아도 괜찮아요~!

클릭 가능한 엘리먼트에게 cursor: pointer 주기

---

.github/workflows/ci.yml

- ci 파일에 pnpm 버전 명시하는 방안으로 수정하였씁니닷
- 확인 후, main 머지하고 Amplify 올라가는지 확인 한 번 부탁두립니다 !!~!
- 이상 없다면 Vercel 영차영차 !!!

Declare pnpm version for CI

---

.github/workflows/ci.yml

chore: no frozen lockfile

---

src/components/Header/Desktop/DesktopHeader.tsx
src/components/Header/header.module.scss

헤더 레이아웃 수정

---

src/components/Footer/Channels/index.tsx
src/components/Footer/OriginFooter/index.tsx
src/components/Footer/OriginFooter/style.ts
src/lib/api/remote/about.ts
src/lib/types/about.ts
src/utils/dateFormat.ts
src/views/AboutPage/components/Member/Card/index.tsx
src/views/AboutPage/components/Member/Card/style.ts
src/views/AboutPage/components/Member/Content/index.tsx
src/views/AboutPage/components/Record/List/index.tsx
src/views/AboutPage/components/common/TabBar/style.ts
src/views/StudyPage/components/Item/index.tsx
src/views/StudyPage/components/Item/style.ts

SPR1 QA (스터디 페이지 / 활동 멤버 / 푸터)

---

src/components/Header/Mobile/HeaderMenu.style.ts
src/components/common/NumberRoller/index.tsx
src/hooks/useInView.ts
src/lib/styles/animation.ts
src/utils/platform.ts
src/views/AboutPage/components/CoreValue/Item/index.tsx
src/views/AboutPage/components/CoreValue/Item/style.ts
src/views/AboutPage/components/CoreValue/List/index.tsx
src/views/AboutPage/components/Member/Section/index.tsx
src/views/AboutPage/components/Record/Item/index.tsx
src/views/AboutPage/components/Record/Item/style.ts
src/views/AboutPage/components/Record/List/index.tsx
src/views/AboutPage/components/common/SectionDescription/index.tsx

보이는 것은 다 구현하였으나, 엣지 케이스가 있을까 두렵습니다 ..
* `useInView` hook : 현재 스크롤 위치에서 컴포넌트가 보이는지에 대한 여부
* `NumberRoller` component : 숫자가 점점 커지는 인터렉션을 하는 컴포넌트

SPR1 QA (인터렉션 / 핵심가치 / 레코드)

---

src/views/AboutPage/components/Member/Content/index.tsx

- 핫픽스 사항이 있어 급하게 달려왔습니다.......:(
다시 배포 반영 부탁드릴게요.. 하하

hotfix: error banner 렌더링 조건

---

src/views/SponsorPage/components/CorporatePartner/index.tsx

close #203 
앰플리튜드 오타 수정합니다! (cclick -> click)

[SP1] 앰플리튜드 오타 수정

---

src/pages/about.tsx

- close #210 
- #183
위 이슈 작업 시 모든 페이지에 PageLayout을 적용했어야 했는데 about페이지에 적용하지 않아서 빌드 오류가 났습니다 ..
그래서 about 페이지에도 적용했습니다!

[SP2] 빌드 오류 수정

---

src/views/ProjectPage/components/RecentProjectList/Item/style.ts
src/views/ProjectPage/components/RecentProjectList/RecentProjectListSkeletonUI/index.tsx
src/views/ProjectPage/components/RecentProjectList/RecentProjectListSkeletonUI/style.ts
src/views/ProjectPage/components/RecentProjectList/index.tsx

프로젝트 캐러셀 SkeletonUI 입니다.
close #257 
|데스크톱|모바일|
|--|--|
|<img width="954" alt="스크린샷 2023-11-05 오후 7 29 24" src="https://github.com/sopt-makers/sopt.org-frontend/assets/62867581/c2a3ca04-67a0-491a-a56c-01d2efe23f06">|<img width="670" alt="스크린샷 2023-11-05 오후 7 29 29" src="https://github.com/sopt-makers/sopt.org-frontend/assets/62867581/2ab2a70c-2f57-497e-8dda-c3d3fd3c0ca5">|
#255 브랜치를 base로 작업했으며 #257 -> #255 로 merge 되는 pr입니다!

[SP2]프로젝트 캐러셀 SkeletonUI

---

src/views/MainPage/components/IntroSection/IntroContent/index.tsx
src/views/MainPage/components/IntroSection/IntroContent/style.ts

- close #298 
- 이미지 `max-width` 707px로 고정
- 올라오는 폭이 좀 더 크도록 y값 수정

[SP2] 메인 가치 섹션 QA

---

src/views/ProjectPage/components/RecentProjectList/index.tsx

- close #300 
- 플레이그라운드 -> 구글 폼으로 링크 변경

[SP2] 릴리즈 소식 알리기 링크 변경

---

src/views/ProjectPage/components/RecentProjectList/Item/style.ts

단 한 줄... `transition: 200ms ease;`을 추가했어요

프로젝트 탭의 사용해보기 버튼에 transition을 추가해요

---

src/lib/constants/project.ts

[SP2] 최근 릴리즈된 프로젝트 데이터 수정

---

src/lib/constants/main.ts
src/lib/types/main.ts
src/lib/types/universal.ts
src/views/MainPage/components/Activity/Card/style.ts
src/views/MainPage/components/Activity/MobileCard/index.tsx
src/views/MainPage/components/Activity/MobileCard/style.ts
src/views/MainPage/components/Activity/index.tsx
src/views/MainPage/components/Activity/style.ts

close #321 
- 기획,디자이너와 협의한 내용으로 액티비티 내용 글자수를 조정
- 768px 부터 보여지는 캐러셀을 기존에 react-slick을 사용하던 것에서 useInfiniteCarousel 사용으로 바꾸었어요.
파트 소개에 사용되는 것을 활용하였습니다.
https://github.com/sopt-makers/sopt.org-frontend/assets/62867581/2d70d030-8d08-442f-a5e6-9d2ca18bc2c7
useInfiniteCarousel을 사용하며 type을 새로 정의하는 부분이 있는데, 괜찮은지 봐주시면 좋겠습니다!

[SP3] 액티비티 내용 수정 및 useInfiniteCarousel 적용

---

src/views/MainPage/components/Activity/MobileCard/style.ts
src/views/MainPage/components/Banner/style.ts
src/views/MainPage/components/Introduce/index.tsx
src/views/MainPage/components/RecruitMessage/index.tsx

[SP3] 메인페이지 최근뉴스 및 리크루팅 QA

---

src/components/Header/Desktop/DesktopHeader.tsx
src/components/Header/Header.tsx
src/components/Header/Mobile/HeaderMenu.style.ts
src/components/Header/Mobile/HeaderMenu.tsx
src/components/Header/Mobile/MobileHeader.tsx
src/components/Header/menuTapList.ts
src/components/Header/style.ts
src/components/Header/types.ts

close #334 
https://github.com/sopt-makers/sopt.org-frontend/assets/62867581/6261b38e-2236-494a-9379-82f9c5a6b303

[SP3] 헤더 디자인 변경

---

src/views/MainPage/components/Banner/style.ts
src/views/MainPage/components/RecruitMessage/style.ts

[SP3] 리크루팅 메시지 마진 조정

---

src/views/MainPage/components/Activity/MobileCard/index.tsx

[SP3] 중복 화살표 제거

---

src/views/MainPage/components/Comment/Card/Desktop/index.tsx
src/views/MainPage/components/Comment/index.tsx
src/views/MainPage/components/Comment/style.ts
src/views/MainPage/components/OwnOrganization/Card/style.ts
src/views/MainPage/components/OwnOrganization/style.ts

[SP3] 자치기구 반응형, 활동후기 글자 부활, 솝트어때요와 최신소식 사이 간격 늘리기

---

src/components/Header/menuTapList.ts

[SP3]헤더 탭 타이틀명 변경

---

src/views/MainPage/components/OwnOrganization/Card/style.ts
src/views/MainPage/components/OwnOrganization/style.ts

[SP3] 자치기구의 makers의 s가 잘리지 않도록 변경

---

src/views/MainPage/components/Comment/Card/Desktop/index.tsx
src/views/MainPage/components/Comment/Cards/index.tsx

[SP3] 솝트어때요? isInView 훅의 마진 진짜 고침

---

src/views/RecruitPage/components/NotificationSection/index.tsx

알림신청 정규식 패턴을 수정하였습니다. 
|기존|변경|
|--|--|
|![image](https://github.com/sopt-makers/sopt.org-frontend/assets/62867581/3a1b54ba-5fdf-442f-91e8-b55a1d3f9c5a)|<img width="1084" alt="스크린샷 2024-01-28 오후 4 40 30" src="https://github.com/sopt-makers/sopt.org-frontend/assets/62867581/ffd8d36a-2a83-4982-b5a9-5edae6dd8e2a">|

[SP4] 알림신청 정규식 패턴 수정

---

src/hooks/useCheckTime.ts
src/views/MainPage/components/TopBanner/index.tsx

ios 에서 timestamp가 정상 작동하지 않는 문제 해결

[S0] ios timestamp 오류 해결

---

src/hooks/useCheckTime.ts
src/lib/api/mock/about.ts
src/views/MainPage/components/TopBanner/style.ts
src/views/RecruitPage/components/ActivityReview/styles.ts
src/views/RecruitPage/components/Contact/index.tsx

- close #365 
* fix: 임원진 정보 linkedin 값 수정
* fix: 활동후기 카드 셋째줄 잘림이슈 해결
* fix: 카운트다운 00:00:00일때 줄바꿈 발생이슈 해결
* chore: 지원하기  배너들 나타나는 시각 3/3 자정 픽스
* fix: /recruit 문의하기 모바일 레이아웃 수정

[SP0] 상용 배포 전 QA

---

src/views/SponsorPage/components/CorporatePartner/index.tsx

- closes #398 
후원 문의하기 버튼 클릭 시 `메일 앱 open` -> `구글폼` 으로 링크 수정하였습니다
`target = _blank` 로 새탭으로 열리도록 했어요 !

[Bugfix] 후원 문의하기 링크 수정

---

src/views/AboutPage/components/Record/Section/index.tsx
src/views/RecruitPage/components/ChapterInfo/index.tsx
src/views/RecruitPage/components/ChapterInfo/style.ts

[Chore] 오타 수정

---

src/components/common/SEO/index.tsx

fix: cd error

---

package.json
pnpm-lock.yaml
src/views/BlogPage/components/OfficialVideo/index.tsx
src/views/BlogPage/components/OfficialVideo/style.ts

`react-youtube` 라이브러리를 활용하여 SOPT 이야기 탭의 공식 영상을 연결했습니다.
- 자동 재생 활성화 
https://github.com/user-attachments/assets/86f7fb05-96fa-436b-ae7d-f6a171481508

[FEAT] SOPT 이야기 공식 영상 연결
