src/components/Footer/Channels/Channels.tsx

- 현재 하단 인스타그램 버튼을 누르면 운영팀 인스타그램 계정이 연결됨

fix: fix instagram click link from timi to official

---

next.config.js
src/views/ProjectDetailPage/types.ts
src/views/ProjectDetailPage/utils/getLinkNameAndSrcWithType.ts
src/views/ProjectPage/types.ts

```js
images: {
domains: [
'sopt-makers.s3.ap-northeast-2.amazonaws.com',
's3.ap-northeast-2.amazonaws.com',
'user-images.githubusercontent.com',
],
},
```

Fix/#36 이미지 도메인 추가 및 LinkType 수정

---

src/hooks/useIsDesktop.ts
src/views/MainPage/components/ActivityDescription/ActivityDescription.tsx
src/views/MainPage/components/ActivityDescription/activity-description.module.scss
src/views/MainPage/components/BannerImage/BannerImage.tsx
src/views/MainPage/components/CorporateLinkedActivities/CorporateLinkedActivities.tsx
src/views/MainPage/components/CorporateLinkedActivities/constants.ts
src/views/MainPage/components/CorporateLinkedActivities/corporate-linked-activities.module.scss
src/views/MainPage/components/CorporatePartner/CorporatePartner.tsx
src/views/MainPage/components/CorporatePartner/corporate-partner.module.scss
src/views/MainPage/components/DetailedInformation/detailed-information.module.scss
src/views/MainPage/components/PartDescription/PartDescription.tsx
src/views/MainPage/components/PartDescription/part-description.module.scss

- 이미지 배너 아래 화살표 클릭 시 스크롤 이동
- 파트 소개 패딩 값 적용 (by 정연)
- SOPT 활동 이미지 설명 글 가운데 정렬 맞추기
- 파트소개, 활동소개 좌측 정렬
- 화살표 세로 가운데 정렬
- SOPT와 함께한 기업 연계 활동 디자인 가이드 반영
메인 페이지 이미지 배경색 그라데이션 적용이 필요합니다.

메인 페이지 기획 QA 반영 및 누락된 디자인 가이드 반영

---

src/hooks/useDevice.ts

- true로 지정하면 메인 페이지 첫 로딩 시 desktop, tablet, mobile에 대한 헤더가 동시에 보이는 이슈 발생

useDevice hook들의 초기값을 false로 변경

---

src/components/Header/Desktop/DesktopHeader.tsx
src/components/Header/Header.tsx
src/components/Header/Mobile/HeaderMenu.style.ts
src/components/Header/Mobile/HeaderMenu.tsx
src/components/Header/Mobile/MobileHeader.tsx
src/components/Header/menuTapList.ts
src/components/Header/types.ts
src/hooks/useHeader.ts
src/hooks/useNoScroll.ts

1. menuList의 프로퍼티를 바꿨어요. id에 라우팅 정보가 들어가있는게 어색했기 때문에요!
1. 타이핑을 선언하였어요. (id를 임의로 추가하는 게 좋을까요-) 그리고 해당 파일을 `components/Header/types.ts` 에 위치시켰습니다!
```typescript
type RoutingMenu = { title: string; route: string };
type AnchorMenu = { title: string; anchor: string };
export type MenuList = Array<RoutingMenu | AnchorMenu>;
```
2. 라우팅 정보가 있는 메뉴들은 `Link` 태그로 치환하였어요. 하지만, 새 탭으로 링크를 보내는 anchor 로직같은 경우에는, `Link` 태그를 쓰는 의미가 없다고 하더군요. 그래서 a 태그를 그대로 사용하였습니다.
2. handleIsSelected 라우팅 기반으로 바꾸기
라우팅 정보를 기반으로 판단하도록 로직을 수정하였습니다!
```typescript
const handleIsSelected = (path: string) => {
return router.pathname.startsWith(path);
};
```
피드백 적극 수용합니다 !!!~

헤더 메뉴 탭 로직 수정

---

next.config.js
src/components/Header/menuTapList.ts
src/hooks/useFetchBase/index.ts
src/hooks/useFetchBase/reducer.ts
src/hooks/useFetchBase/types.ts
src/lib/project.ts
src/lib/review.ts
src/views/MainPage/MainPage.tsx
src/views/MainPage/assets/arrow_right_white.svg
src/views/MainPage/components/ActivityDescription/activity-description.module.scss
src/views/MainPage/components/ActivityReview/ActivityReview.tsx
src/views/MainPage/components/ActivityReview/activity-review.module.scss
src/views/MainPage/components/ActivityReview/hooks/useFetch.ts
src/views/MainPage/components/ActivityReview/utils/parsePartToKorean.ts
src/views/MainPage/components/CorporateLinkedActivities/corporate-linked-activities.module.scss
src/views/MainPage/components/SoptHistory/sopt-history.module.scss
src/views/MainPage/components/index.ts
src/views/MainPage/main-page.module.scss
src/views/ProjectPage/hooks/useFetch.ts
src/views/ProjectPage/types.ts
src/views/ReviewPage/ReviewPage.tsx
src/views/ReviewPage/components/Description/index.tsx
src/views/ReviewPage/components/Reviews/index.tsx
src/views/ReviewPage/components/Reviews/style.ts
src/views/ReviewPage/components/TabBar/index.tsx
src/views/ReviewPage/components/TabBar/style.ts
src/views/ReviewPage/components/index.ts
src/views/ReviewPage/hooks/useFetch.ts
src/views/ReviewPage/libs/constants.ts
src/views/ReviewPage/types/index.tsx

- https://github.com/sopt-makers/sopt.org-frontend/pull/83 사항 머지하여 진행하였습니다. 제 커밋만 보시면 될 것 같아요 !
- `MainPage/components/ActivityReviews` 컴포넌트에요. 위아래에서 컴포넌트를 잘게 안쪼개길래, 저도 그냥 다 넣었어요. 피드백 환영합니다!
- 저엉말 반응형 작업 오랜만에 해서 처참한 css 능력이 탄로나었습니다.. 뚝딱 하고 작업 도와주고 싶었는데😭😭 미안해요
https://user-images.githubusercontent.com/47105088/226116370-fc0f3597-f3b2-46a5-b0c3-5be3df45efea.mp4
https://user-images.githubusercontent.com/47105088/226116377-dcc14a47-8a63-4232-9d5a-6fc2e052cec0.mp4
- `useFetch` 훅이랑 util 폴더를 결국 컴포넌트 폴터 내에 생성했어요 ..! 컴포넌트 내에서만 사용할 것 같아서요! 피드백 환영합니닷
- 데스크탑 뷰의 양 옆 마진을 제외한 메인 width 가 1100px로 설정되어 있었는데, 피그마에는 1200이더군요?? 활동후기 레이아웃이 깨지길래 1100px -> 1200px 변경하였습니다 (3군데)
- scss 좋네요 ,,! css-in-js와 장단점이 뚜렷한 것 같아요 하하

활동후기 메인 뷰 추가

---

src/hooks/useBooleanState.ts
src/hooks/useIntersectionObserver.ts
src/hooks/useStackedFetchBase.ts
src/hooks/useStackedFetchBase/index.ts
src/hooks/useStackedFetchBase/reducer.ts
src/hooks/useStackedFetchBase/types.ts
src/lib/review.ts
src/styles/textEllipsis.ts
src/views/ProjectPage/hooks/useInfiniteScroll.ts
src/views/ReviewPage/ReviewPage.tsx
src/views/ReviewPage/components/Reviews/index.tsx
src/views/ReviewPage/components/Reviews/style.ts
src/views/ReviewPage/hooks/useFetch.ts
src/views/ReviewPage/hooks/useInfiniteScroll.ts

- 프로필의 훅과 연동할 수 있는 것(`useIntersectionObserver`)은 두고, 변형되는 것은 새로 선언하였어요(`useInfiniteScroll`)
- `useFetchBase`에서 변형하여, 계속해서 쌓이는 데이터를 구성하기 위해 `useStackedFetchBase` 훅을 새로 선언하였어요
- 스크롤 로딩 뷰는 프로필 페이지의 스피너를 따와서 구성하였습니다!
https://user-images.githubusercontent.com/47105088/228190775-be0d1b61-0164-47c4-ab48-c0ae2867397c.mp4
중간 리뷰 환영합니다 !~

sp0 활동 후기 무한 스크롤

---

src/lib/api.ts
src/lib/project.ts
src/utils/const/client.ts

서버 도메인을 BASE_URL로 제공했습니다! 
하는 김에 타임아웃도 매직넘버를 빼고 상수로 만들었습니다!
언젠가 저 클라이언트 자체를 어디선가 export하는 것도 괜찮을 것 같습니다
현재 https://api-dev.sopt.org/projects 로 요청을 보내면 500이 터져서, 이것을 머지하면 프로젝트 탭에서 오류가 발생합니다! 원인을 함 파악해 보아야 할 것 같습니다

refactor: give base url based on node environment

---

src/lib/api/mock/about.ts
src/lib/types/about.ts

about API와 members API를 분리했습니다.
API가 두 개 생긴 것입니다!
이 API를 호출하는 건 그 섹션 내에서 할 지 AboutPage.tsx에서 할 지 고민해 보아야 할 것 같습니다..!! 물론 나중에는 한번에 할 것이지만요
```ts
const getMemberInfo = async (part?: Part): Promise<GetMembersInfoResponse>
```

chore: split about api and members api

---

src/components/common/Flex/index.tsx
src/lib/api/mock/about.ts
src/views/AboutPage/AboutPage.tsx
src/views/AboutPage/components/CoreValue/Item/index.tsx
src/views/AboutPage/components/CoreValue/Item/style.ts
src/views/AboutPage/components/CoreValue/List/index.tsx
src/views/AboutPage/components/CoreValue/Section/index.tsx
src/views/AboutPage/components/CoreValue/Section/style.ts
src/views/AboutPage/components/common/SectionDescription/index.tsx
src/views/AboutPage/components/common/SectionTitle/index.tsx

About 페이지의 핵심 가치 섹션을 구현합니다.
* #111 
추가적인 사항은 코멘트로 작성하겠습니다!
* Flex 라는 컴포넌트를 만들어서, Flex 관련해서 반복 선언하는 부분을 더 직관적으로 옮겨보려는 시도를 하였습니다. 그리고 (개인적으로) 다른 div 간에 마진을 주는 것보다 flex로 싸고 gap을 주는 걸 좋아하는데요, (-) 돔트리가 더 깊어진다 (+) 프로그래머가 보고 수정하기 편하다 라고 생각합니다.. 당신의 의견은 어떠십니까?
* 각 섹션의 제목은 모두 서식이 같아서 `SectionTitle` 안에다가 넣으면 될 것 같습니다!

feat: About 페이지의 핵심 가치 섹션 구현

---

next.config.js
src/lib/api/mock/about.ts
src/lib/api/remote/review.ts
src/lib/types/about.ts
src/lib/types/review.ts
src/lib/types/universal.ts
src/views/AboutPage/AboutPage.tsx
src/views/AboutPage/components/Cirriculum/Content/index.tsx
src/views/AboutPage/components/Cirriculum/Content/style.ts
src/views/AboutPage/components/Cirriculum/Section/index.tsx
src/views/AboutPage/components/common/TabBar/index.tsx
src/views/AboutPage/components/common/TabBar/style.ts
src/views/AboutPage/constant/taps.ts
src/views/AboutPage/hooks/useFetch.ts
src/views/MainPage/lib/useTabs.ts
src/views/ReviewPage/ReviewPage.tsx
src/views/ReviewPage/components/Reviews/index.tsx
src/views/ReviewPage/components/TabBar/index.tsx
src/views/ReviewPage/hooks/useFetch.ts
src/views/ReviewPage/libs/constants.ts

- 커리큘럼 섹션을 구현합니다
- 릴레이를 위하여 https://github.com/sopt-makers/sopt.org-frontend/pull/113 에서 브랜치를 파 진행하였습니다 (이후 머지 시에 develop으로 순차적으로 머지하면 될 듯 합니다!)
- Flex 컴포넌트 정말 잘 썼습니다🙏🏼🙏🏼
https://user-images.githubusercontent.com/47105088/235663147-d685d0ca-be5d-4ccb-8059-76eddeabfb44.mp4
- 특이사항 하나는, 리뷰 페이지에서 서진이가 제작해둔 `TapType` 의 재활용을 위해 `types/universal` 로 옮기고, "전체가 없는 탭 타입"과 "전체가 있는 탭 타입"을 나누었습니다. 이를 위해 타입명도 바꾸게 되었는데, 피드백 마음껏 주셔도 좋습니다! 5b3e05f366a5676d45eb119563f1d75ef50139f0 해당 커밋에 작업이 담겨져 있습니다

feat: About 탭 커리큘럼 섹션 구현

---

src/views/AboutPage/AboutPage.tsx
src/views/AboutPage/components/Member/Card/index.tsx
src/views/AboutPage/components/Member/Card/style.ts
src/views/AboutPage/components/Member/Content/index.tsx
src/views/AboutPage/components/Member/Content/style.ts
src/views/AboutPage/components/Member/Section/index.tsx
src/views/AboutPage/hooks/useFetchMemeber.ts
src/views/ProjectPage/components/filter/DesktopFilter.tsx
src/views/ProjectPage/components/filter/MobileFilter.tsx
src/views/ProjectPage/components/filter/MobileFilterModal.tsx
src/views/ProjectPage/components/filter/ProjectFilter.tsx

- 멤버 패칭 부분, 구현하였습니다
https://user-images.githubusercontent.com/47105088/236119405-596ef92c-099c-474d-a5e9-89088d02c84b.mp4
해당 섹션이 맨 아래에 위치한 섹션이기 때문에, About 탭에서 lazy loading 을 하여 최후순위로 렌더링 하고자 하는데, 어떻게 생각하실니다까요!?

#111 about 탭 멤버 섹션 구현

---

src/lib/api/mock/about.ts
src/lib/types/about.ts
src/pages/study.tsx
src/utils/dateFormat.ts
src/views/AboutPage/AboutPage.tsx
src/views/AboutPage/components/Record/Item/index.tsx
src/views/AboutPage/components/Record/Item/style.ts
src/views/AboutPage/components/Record/List/index.tsx
src/views/AboutPage/components/Record/Section/index.tsx
src/views/StudyPage/StudyPage.tsx
src/views/StudyPage/components/Item/index.tsx
src/views/StudyPage/components/Item/style.ts
src/views/StudyPage/components/List/index.tsx
src/views/StudyPage/components/List/style.ts
src/views/StudyPage/components/Section/index.tsx
src/views/StudyPage/components/Section/style.ts
src/views/StudyPage/hooks/useFetch.ts
src/views/StudyPage/index.tsx

어바웃 페이지의 record 섹션과 스터디 페이지를 추가합니다.
스터디 관련 API도 추가했습니다.
D | T | M
--|--|--

feat: implement about pages' study api

---

src/components/Footer/OriginFooter/style.ts
src/components/corporate/JobPostingCard/index.tsx
src/components/corporate/JobPostingCard/style.ts
src/lib/api/index.ts
src/lib/api/mock/job.ts
src/lib/types/job.ts
src/lib/types/universal.ts
src/styles/global.ts
src/styles/textEllipsis.ts
src/views/AboutPage/components/Member/Card/style.ts
src/views/AboutPage/components/common/TabBar/style.ts
src/views/FAQPage/components/contact/ContactInfo.tsx
src/views/FAQPage/components/contact/index.tsx
src/views/FAQPage/components/faq/QuestionBox.tsx
src/views/FAQPage/components/faq/index.tsx
src/views/MainPage/MainPage.tsx
src/views/MainPage/components/CorporateJob/FieldTabs/index.tsx
src/views/MainPage/components/CorporateJob/FieldTabs/style.ts
src/views/MainPage/components/CorporateJob/JobPostings/index.tsx
src/views/MainPage/components/CorporateJob/JobPostings/style.ts
src/views/MainPage/components/CorporateJob/index.tsx
src/views/MainPage/components/CorporateJob/style.ts
src/views/MainPage/lib/useTabs.ts

- 후원 공고 섹션을 구현하였습니다.
- react-query를 사용해보았어요 ! Suspense로 스피너를 부착해서 로딩 관심사를 분리하였어요
- `JobPostingCard` 컴포넌트를 component 폴더에 구성하였어요. 피그마 components 로 분리되었기 때문에 이후에 재사용 가능성이 있을 수 있다고 판단하였기 때문입니다.!
- useTab 커스텀 훅을 재사용하였어요
https://github.com/sopt-makers/sopt.org-frontend/assets/47105088/ae999a8c-a098-47af-902c-9db160fa0c8a
- 화이팅💥💥💥💥

SPR 2 후원 공고 섹션 개설

---

next.config.js
src/components/Header/Desktop/DesktopHeader.tsx
src/components/Header/Mobile/HeaderMenu.style.ts
src/components/Header/menuTapList.ts
src/lib/api/remote/sopticle.ts
src/lib/styles/animation.ts
src/utils/sanitize.ts
src/views/ReviewPage/components/TabBar/style.ts
src/views/SopticlePage/components/TabBar/style.ts

QA 작업 사항을 반영합니다.
너무 많슴다 .... 아래 코멘트를 참고해주시면 좋을 것 같아요 .!!
- `https://`로 시작하지 않아서 렌더링되지 않는 이미지에 대한 처리를 합니다.
- Mobile Header에서 삐뚤어진 마음을 바로잡아줍니다.
- 지원하기 버튼의 문구를 변경하고 예쁜 네모를 둘러 줍니다.
- 데스크탑 헤더에서 호버하면 서브메뉴가 나타나도록 수정합니다. (기존에는 클릭해야 나타나는 형태)
- 데스크탑 헤더에서 서브메뉴가 나타날 때 애니메이션이 등장하도록 수정합니다.
- 데스크탑 헤더에서 호버하면 밑줄이 등장하도록 합니다.
- 솝티클, 리뷰 탭의 탭에서도 호버하면 배경색상이 변경되도록 합니다.

솝티클 릴리즈 QA

---

.babelrc
package.json
pnpm-lock.yaml
src/components/Header/Desktop/DesktopHeader.tsx
src/components/corporate/JobPostingCard/style.ts
src/views/SopticlePage/components/Sopticles/style.ts

위 세가지 컴포넌트에 호버 상태를 추가합니다
|지원하기버튼|솝티클카드|후원카드|
|-|-|-|
|![2023-06-22 09 12 54](https://github.com/sopt-makers/sopt.org-frontend/assets/48249505/6e2bc5f7-616a-4ea1-b2f8-f2143bc51b62)|![2023-06-22 09 13 31](https://github.com/sopt-makers/sopt.org-frontend/assets/48249505/1973bb1b-0ee8-4e02-9f1e-87e3699aefd7)|![2023-06-22 09 15 07](https://github.com/sopt-makers/sopt.org-frontend/assets/48249505/713d9d47-e11e-4003-ae27-43c9449fb772)|
솝티클카드에게 효과를 줄 때, 호버된 부모의 자식에게 적용하는 방법을 보다가 (자식 선택자를 `nth-child`나 `div`/`p` 등으로 쓰는건 nono..), https://stackoverflow.com/questions/41007060/target-another-styled-component-on-hover 이 글을 발견하여 여기 있는대로 해 보았습니다. 
```ts
const Wrapper = styled.div`
&:hover ${Button} {
display: none;
}
`
```
```ts
const Button = styled.button`
${Wrapper}:hover & {
display: none;
}
`;
```
그 …

SPR2 QA : hover 상태 추가

---

src/lib/api/remote/about.ts
src/views/AboutPage/components/Member/Section/index.tsx
src/views/AboutPage/components/Record/Section/index.tsx

기존에는 about 탭에서 32기의 정보를 보여주고 있었는데, 33기 정보로 교체합니다.

feat: show DO SOPT in about tab

---

src/views/ProjectDetailPage/ProjectDetail.style.tsx

프로젝트 설명 부분에 white-space: pre-wrap 속성을 추가합니다!
이미 배포버전엔 반영되었어요 ..
머지할 땐 feat/#153-recruit 먼저 머지한 후, 
이 PR의 base브랜치를 develop으로 바꾸어 rebase 머지할 계획입니다!

fix: project description's white-space

---

src/views/ProjectPage/components/project/ProjectCard.tsx

close #164 
링크가 4개가 넘어가면 링크에서 넘치는 이슈가 발생해 index 3번째 링크 요소까지만 보여지도록 임시로 설정해두었습니다.
추후에 넘치는 링크 요소들을 어떻게 처리할지는 논의가 필요합니다!

[SP0] 프로젝트 링크 넘침 이슈

---

src/views/ProjectPage/components/project/ProjectCard.tsx
src/views/ProjectPage/components/project/project-card.module.scss

close #165 
`object-fit : cover` 속성을 부여했습니다.
|전|후|이미지 16:9 ration 조정|
|--|--|--|
|<img width="356" alt="image" src="https://github.com/sopt-makers/sopt.org-frontend/assets/62867581/7d463257-dad1-4255-9670-a7ceabdd062a">|<img width="348" alt="image" src="https://github.com/sopt-makers/sopt.org-frontend/assets/62867581/1b3c1a3a-6818-482a-a156-b6d860e2a517">|<img width="364" alt="image" src="https://github.com/sopt-makers/sopt.org-frontend/assets/62867581/bf81bace-7b57-414e-84ac-b6c2d17b02a7">|
공홈(176px)과 플레이그라운드와는 높이(208px)가 달라서 이미지 중 일부 보이지 않는 부분이 있을 수는 있습니다. 추후 개편때 디자이너분과 얘기를 해보면 좋을 것 같아요

[SP0] 프로젝트 이미지 눌림 이슈

---

src/views/MainPage/components/ActivityDescription/ActivityDescription.tsx
src/views/SopticlePage/components/Sopticles/style.ts

close #174 
솝티클 썸네일 이미지 찌부 이슈를 해결했습니다.
|전|후|
|--|--|
|<img width="1356" alt="image" src="https://github.com/sopt-makers/sopt.org-frontend/assets/62867581/06f0b04d-8cfb-4edc-a767-30527007c5d8">|<img width="1333" alt="image" src="https://github.com/sopt-makers/sopt.org-frontend/assets/62867581/827f353d-a8dc-43df-a058-d7fea3889f07">|
메인페이지 ActivityDescription 부분에서 key가 없어서 CI가 실패하는 에러가 났어요! 서진이 `폴더구조 변경 리팩토링 PR` 에서 해당 커밋을 본 기억이 있어서 똑같이 작업했습니다! 다만,,,  data가 {data}로 되어있지 않아서 data 그대로 출력되는 오류가 있어서 이부분을 수정해 작업했고, 서진이 pr에도 언급해두었습니다!!

[SP1] 솝티클 썸네일 이미지 찌부 이슈

---

package.json
pnpm-lock.yaml
src/views/MainPage/MainPage.tsx
src/views/RecruitPage/RecruitPage.tsx
src/views/RecruitPage/components/BottomLogo/index.tsx
src/views/RecruitPage/components/NotificationSection/index.tsx

* [fix: hide banner and recruit section](https://github.com/sopt-makers/sopt.org-frontend/commit/ced21a32f48cd8eeaf48019f9ec800fb847078c6) : #176  리크루팅 배너와 지원서 쓰러가기 버튼을 변경합니다. 일단은 이렇게 하고 나중에 더 슬기로운 방법을 함께 생각해 보아요..!!
* [fix: remove styled-components installation](https://github.com/sopt-makers/sopt.org-frontend/commit/07401a2dfc529ac53e127feae8001ab0d533ddae) : `styled-components` 라이브러리가 설치된 것을 삭제합니다. (아마 디벨롭 브랜치에 머지하며 뭔가 꼬인 것 같아요 ..!)
* [fix: NotificationSection 관련 스타일 추가](https://github.com/sopt-makers/sopt.org-frontend/commit/be326ab109d8b36c5cb4955c4d64cbdc97300272) : #177 내용을 반영합니다.
릴리즈 빌드를 위해 머지할게요 ..!!
이것이 SP0으로써 main에 머지되는 마지막 PR이 될 것 같습니당
그리고 다음부터는 가급적 한 PR에 이슈 하나씩 하겠습니다 ...

[SP0] 리크루팅 배너와 지원 버튼 가리기, 리크루팅 탭 알림 버튼 변경, 디벨롭 브랜치에서 누락된 사항 추가

---

src/views/RulesPage/components/UnderlinedText/UnderlinedText.style.tsx

close #186 
회칙 페이지에 블루 컬러가 사용되어서 #fcfcfc 색상으로 변경했습니다!
|전|후|
|--|--|
|<img width="491" alt="image" src="https://github.com/sopt-makers/sopt.org-frontend/assets/62867581/ff5ca30b-42a0-4d59-a5b7-3ccf8d28e18a">|<img width="477" alt="image" src="https://github.com/sopt-makers/sopt.org-frontend/assets/62867581/6b143c73-c188-4c0d-8b87-a7eedc0d8b21">|

[SP1] 솝트 회칙 페이지 컬러 변경

---

src/components/corporate/JobPostingCard/index.tsx
src/components/corporate/JobPostingCard/style.ts
src/views/MainPage/components/ActivityReview/ActivityReview.tsx
src/views/MainPage/components/ActivityReview/activity-review.module.scss
src/views/MainPage/components/DetailedInformation/DetailedInformation.tsx
src/views/MainPage/components/DetailedInformation/detailed-information.module.scss
src/views/MainPage/components/RecruitFloatingBanner/RecruitFloatingBanner.tsx
src/views/ProjectPage/components/project/ProjectCard.tsx
src/views/ProjectPage/components/project/project-card.module.scss
src/views/RecruitPage/components/ActivityReview/ActivityReview.tsx
src/views/RecruitPage/components/ActivityReview/styles.ts

- close #181
img 태그로 쓰인 이미지를 모두 next/image의 Image 컴포넌트로 변경합니다!
1. 간단한 아이콘들은 image 태그 대신에 svg 그대로 써도 좋을 것 같아요 ..!!

[SP1] img 태그로 쓰인 이미지를 모두 next/image의 Image 컴포넌트로 변경

---

src/lib/constants/googlesheet-env.ts
src/pages/api/register.ts

- close #192 
구글시트에서 뭔가 정책을 바꿔서, private key에 있는 \n에 대해 특별한 처리를 해주지 않으면 에러가 나게 되었스빈다..
https://stackoverflow.com/questions/74131595/error-error1e08010cdecoder-routinesunsupported-with-google-auth-library
22일 전에 올라온걸 보니 따끈따끈한 이슈인 것 같긴 한데, 왜 그동안 잘 됐던 걸까요 ..?

[SP1] 리크루팅 알림받기 API에서 500 에러가 나는 것을 해결한다.

---

src/views/RecruitPage/components/ActivityReview/ActivityReview.tsx
src/views/RecruitPage/components/ChapterInfo/index.tsx
src/views/RecruitPage/components/FAQ/index.tsx
src/views/RecruitPage/components/NotificationSection/index.tsx
src/views/RecruitPage/components/common/Tabs/index.tsx
src/views/SponsorPage/components/CorporateJob/FieldTabs/index.tsx
src/views/SponsorPage/components/CorporateJob/JobPostings/index.tsx
src/views/SponsorPage/components/CorporateLinkedActivities/index.tsx
src/views/SponsorPage/components/CorporatePartner/index.tsx

close #197 
리쿠르팅, 후원페이지 앰플리튜드 트래킹 코드를 심었습니다!
아래 두개의 탭은 같은 컴포넌트를 사용해서 props로 트래킹 코드 네임(`amplitudeTrackingName`)을 넘겨주도록 수정하였습니다!
```js
<S.TabBar>
{allTabs.map((tab) => (
<Tab
key={tab.value}
onClick={() => {
onTabClick(tab.value);
track(amplitudeTrackingName, { part: tab.value });
}}
tab={tab}
selected={selectedTab === tab.value}
/>
))}
</S.TabBar>
```

[SP1] 리쿠르팅, 후원페이지 amplitude tracking code 심기

---

src/views/MainPage/components/ActivityReview/ActivityReview.tsx
src/views/MainPage/components/DetailedInformation/DetailedInformation.tsx
src/views/ProjectPage/components/project/ProjectCard.tsx
src/views/ReviewPage/components/Content/index.tsx
src/views/ReviewPage/components/Reviews/index.tsx

- close #201 
앰플리튜드 이벤트 트래킹을 붙입니다.
여러분 Part 등은 다 영어로 가도록 하셨나여 ..???
그리고 click 이벤트를 한땀한땀 붙이다가 생각한 것은, 엘리먼트의 프로퍼티로 넣어둬도 괜찮을 것 같다는 생각이 들어용
```jsx
<div onClick={()=>track("click_review_detail")} />
```
```jsx
<div amplitude-click-track="review_detail" />
```
어딘가에서
```js
window.addEventListener('click', (e)=> {
// 클릭 당한 엘리먼트에게 amplitude-click-track 프로퍼티가 있는지 확인하고,
// 있으면 track(`click_${그것}`); 쏴주기!
});
```
이벤트 위임 방식인데요, 클릭리스너 하나라 부하가 심할 것 같지도 않고 앞으로 개발하기도 편할 것 같아서 의견을 내 봅니다!!
(물론 커스텀 파라미터 전해줘야 할 때는 컴포넌트에서 직접 쏴주거나, 다른 방법을 찾아보아야 합니당...)
@solar3070 @f0rever0  님 의견을 듣고 싶습니다!!!!

[SP1] 앰플리튜드 이벤트 트래킹 - 메인페이지, 활동후기, 프로젝트

---

.github/workflows/ci.yml

- close #212 
CI 스크립트란 해당 PR이 머지 가능한지 확인하는 스크립트로, CI 스크립트에 적힌 step들을 통과하지 못하면 머지가 불가능합니다.
- AS-IS : CI 스크립트에서 lint까지 검사합니다.
- TO-BE: CI 스크립트에서 빌드가 잘 되는지도 봅니다.
**두번째 커밋만 봐주세요!!!!!**
|빌드 안 됨|빌드 잘 됨|
|--|--|
|<img width="300" alt="스크린샷 2023-10-10 오후 1 10 07" src="https://github.com/sopt-makers/sopt.org-frontend/assets/48249505/99e227cc-e6a2-4d73-a346-70d9aec45690">|<img width="300" alt="스크린샷 2023-10-10 오후 1 15 03" src="https://github.com/sopt-makers/sopt.org-frontend/assets/48249505/a4a5ffca-d594-4541-8eca-12dd83afe4e4">|
다 돌아가는데 최대 2분정도 걸릴 것 같아용 .. 
너무 급하면 그냥 머지해도 될 것 같습니다!!
이 과정에서 repository secret에 저희 환경변수값들을 집어넣어 두었습니다!
앰플리튜드 키는 혜준언니 테스트키를 넣었고, api url은 프로덕션으로 넣어두었어요

[SP2] CI 스크립트에 빌드 step 추가

---

src/components/common/HTMLHead/index.tsx
src/pages/_app.tsx
src/views/ProjectDetailPage/ProjectDetailPage.tsx

head 태그들을 하나의 컴포넌트로 분리했습니다! 그리고 프로젝트 url 을 공유할때 og 가 다르게 보이도록 하였어요!
(로컬에서 테스트를 할때, image가 적용이 안된채로 나오는데,,, 이거는 배포하고 다시 확인해볼게요!)
공통 컴포넌트로 분리해보았는데, 폴더 구조가 어떤지 피드백 부탁드려요~

feat : head 태그 컴포넌트로 분리 및 프로젝트별 og tag 적용

---

src/views/RecruitPage/components/NotificationSection/index.tsx

기존에 사진과 같이 이메일 형식에 맞지 않은 값이 저장이 되어서 pattern 을 추가해 이를 해결했습니다!
다음과 같이 input 자체에 경고 메시지가 뜹니다!

[SP1] 리쿠르팅 알림 신청 입력란에 이메일 pattern 추가

---

src/components/Header/Desktop/DesktopHeader.tsx
src/components/common/Select/style.ts
src/views/ProjectPage/styles.ts

- close #238 
- 해당 이슈 [논의 스레드](https://sopt-makers.slack.com/archives/C042T8GEA0Y/p1698133445535069)입니다.
- 네비게이션 글씨 사이 간격이 마진(이미지 마우스 올린 부분)인데 해당 부분을 클릭해도 반응이 없는 상태입니다. 아래 흰 선으로 인해 클릭이 가능할 것처럼 보이지만 클릭이 되지 않고 있어 UX상 좋지 않다고 생각하였습니다.
- 기획과 논의 후 클릭 범위를 흰 선과 맞추기로 하였습니다.

[SP2] 네비게이션 클릭 범위 수정

---

src/components/common/Select/style.ts
src/lib/constants/project.ts
src/views/ProjectPage/ProjectPage.tsx
src/views/ProjectPage/components/RecentProjectList/index.tsx
src/views/ProjectPage/components/project/ProjectList.tsx
src/views/ProjectPage/components/project/project-list.module.scss
src/views/ProjectPage/styles.ts

카드 디자인 변경은 https://github.com/sopt-makers/sopt.org-frontend/issues/234 이슈에서!
- close #236 
- 프로젝트 탭 레이아웃을 변경합니다!
- 글자 크기 조정하고 마진 준 것이 거의 다입니다..
- #219 에서 미처 다 하지 못한 드롭다운 반응형 작업도 하였습니다!
* scss로 되어 있는 부분은 마이그레이션하지 않고 그 파일에 이어서 작업했습니다!
* 이 PR은 #235 가 있는 브랜치를 향해 쐈지만, 머지할 때 develop으로 변경할 예정입니다.

[SP2] 프로젝트 탭 레이아웃 스타일 반영

---

src/lib/api/remote/project.ts
src/lib/constants/project.ts
src/lib/types/project.ts
src/views/ProjectPage/ProjectPage.tsx
src/views/ProjectPage/components/RecentProjectList/index.tsx
src/views/ProjectPage/hooks/useFetch.ts
src/views/ProjectPage/styles.ts

- close #242
플랫폼으로도 필터링할 수 있도록 합니다!
https://api-dev.sopt.org/api-docs#/Project/ProjectsController_getProjects
develop에서 따온 거라, 현재 작업 범위 밖의 스타일은 작업되지 않았습니다!

[SP2] 프로젝트 탭에 플랫폼 필터 추가

---

src/components/common/Carousel/style.ts
src/components/common/Select/index.tsx
src/components/common/Select/style.ts
src/views/ProjectPage/ProjectPage.tsx
src/views/ProjectPage/components/RecentProjectList/Carousel/index.tsx
src/views/ProjectPage/components/RecentProjectList/Item/style.ts
src/views/ProjectPage/components/RecentProjectList/index.tsx
src/views/ProjectPage/components/project/ProjectCard/index.tsx
src/views/ProjectPage/styles.ts

- close #249 
#249 에 있는 내용들을 수정합니다!

[SP2] 프로젝트 페이지 디테일한 디자인 수정 2

---

src/assets/icons/ic_ellipse_green.svg
src/views/ProjectPage/components/project/ProjectCard/ServiceInfo/index.tsx
src/views/ProjectPage/components/project/ProjectCard/ServiceInfo/style.ts
src/views/ProjectPage/components/project/ProjectCard/index.tsx
src/views/ProjectPage/components/project/ProjectCard/style.ts

[SP2] 프로젝트 서비스 이용 가능 및 창업중 정보 보여주기

---

src/pages/_app.tsx
src/views/BlogPage/BlogPage.tsx
src/views/BlogPage/components/BlogPost/Header/index.tsx
src/views/BlogPage/components/BlogPost/index.tsx
src/views/BlogPage/components/BlogPostList/index.tsx
src/views/BlogPage/components/BlogPostList/style.ts
src/views/BlogPage/components/BlogTab/index.tsx
src/views/BlogPage/components/BlogTab/types.ts
src/views/BlogPage/components/EmptyBlogPostList/index.tsx
src/views/BlogPage/components/EmptyBlogPostList/style.ts
src/views/BlogPage/hooks/queries/useGetResponse.ts
src/views/ProjectPage/hooks/queries/index.ts

_app.tsx 파일에서 
```js
export const queryClient = new QueryClient({
defaultOptions: {
queries: {
retry: 0,
suspense: true,
refetchOnWindowFocus: false,
refetchOnMount: false,
refetchOnReconnect: false,
},
},
});
```
를 적용하면서 `suspense: true,` 으로 블로그 페이지에서도 query를 suspense를 사용하는 방식으로 구조를 변경하였습니다.
suspense를 적용하면 suspense 하위 컴포넌트에서 데이터 패칭을 해와야해서 기존에 BlogPage/index에 받아오던 것을 `BlogPostList` 컴포넌트 내에서 받아오도록 수정하였습니다.

[SP2] 블로그 페이지 Suspense 적용

---

src/views/ProjectPage/components/project/ProjectCard/style.ts

- close #261 
- 요소간 간격이 일부 안맞는 부분이 있어 수정합니다.

[SP2] 프로젝트 카드 디자인 수정

---

src/components/common/Carousel/index.tsx
src/components/common/Carousel/style.ts
src/views/ProjectPage/components/RecentProjectList/Carousel/index.tsx
src/views/ProjectPage/components/RecentProjectList/Item/style.ts

- close #265 
**[ 디자인 QA ]**
피그마를 확인했을 때 캐러셀 옆이 **블러 처리가 될 때**가 _슬라이드 아이템이 잘려서 보이는 경우_ 와 _슬라이드를 넘길 때_ 라고 생각됩니다.
|슬라이드 아이템이 잘려서 보이는 경우|슬라이드를 넘길 때 |
|--|--|
|![image](https://github.com/sopt-makers/sopt.org-frontend/assets/63948884/ee58ebee-fa09-470c-a254-e35420636a2a)|![image](https://github.com/sopt-makers/sopt.org-frontend/assets/63948884/1efaf3fd-a4ec-424c-b3b3-7767c65c849f)|
**[ 기존 ]** 
https://github.com/sopt-makers/sopt.org-frontend/assets/63948884/7dbfa3a3-f94c-409e-bc3a-062859b49927
**[ 수정 후 ]**
https://github.com/sopt-makers/sopt.org-frontend/assets/63948884/d679e2a1-135d-42f7-8b30-bd91adf2ef5a
- 아래 QA의 경우에는 제 컴퓨터에서는 나타나지 않던 현상이어서 확인이 어렵습니다.. dev 페이지 배포 후 확인을 부탁드려야 할 것 같습니다.

[SP2] 프로젝트 탭 캐러셀 블러 스타일 수정

---

src/views/BlogPage/hooks/useInfiniteScroll.ts
src/views/RecruitPage/components/ActivityReview/index.tsx

- close #267 
CI 워닝이 뜨던 것을 고쳤습니다!
리크루팅 탭의 활동 후기 부분이 주석으로 봉인되어 있더라고요 ..!! 그것으로부터 풀어주었습니다.
혹시 이것의 히스토리를 아시는 분이 있으신가요?
봉인을 해제해도 되는게 맞는지 알아봐야 할 것 같아요
- useBooleanState 훅을 사용하면, 그것이 리턴하는 setTrue, setFalse 함수를 useEffect에서 호출했을 때 의존성 배열에 넣어주어야 하네요 .. 그런데 의미상 필요하지 않은 것 같아서 useState를 쓰는 코드로 변경했는데, 더 좋은 해결방법이 있다면 말씀해 주시면 감사하겠습니다!

[SP2] CI 에러 고치기, 리크루팅 탭 활동후기 복원

---

src/components/common/Carousel/style.ts

[SP2] 모바일에서도 프로젝트 탭 캐러셀의 화살표가 보여 깨지는 현상을 수정합니다.
display:hidden 같은건 없고 .. none 입니당...

[SP2] 모바일에서도 프로젝트 탭 캐러셀의 화살표가 보여 깨지는 현상 수정

---

src/components/common/Carousel/style.ts
src/views/ProjectPage/components/RecentProjectList/Carousel/index.tsx
src/views/ProjectPage/components/RecentProjectList/Item/style.ts
src/views/ProjectPage/components/RecentProjectList/RecentProjectListSkeletonUI/index.tsx
src/views/ProjectPage/components/RecentProjectList/RecentProjectListSkeletonUI/style.ts
src/views/ProjectPage/components/RecentProjectList/index.tsx
src/views/ProjectPage/styles.ts

- close #276 
아이패드에서 새로고침시 아래와 같이 렌더링이 제대로 되지 않는 이슈가 있었습니다. 맥북 및 안드로이드 폰에서는 가끔 일어나는 듯하고 아이패드에서는 새로고침마다 반복됩니다. 현재 배포 환경에서 보이고 있는 오류이기 때문에 hotfix를 달았습니다. 
https://github.com/sopt-makers/sopt.org-frontend/assets/63948884/35e57ab5-b36a-46af-b587-b1663cf1a224
에러의 근원은 프로젝트 페이지의 최근 출시된 프로젝트 목록 컴포넌트였습니다. 여기서는 `useQuery`를 사용 중이고, `suspense`를 통해 데이터 로딩시 fallback UI를 보여주고 있습니다. 하지만 데이터를 로드하는 부분이 서스펜스 바운더리 바깥에 있었기 때문에 에러가 발생하였습니다. 
- 원인 찾는다고 잠을 못자서.. 지금 자러 갑니다.. 가능한 한 빨리 머지하는 게 좋을 것 같은데 이상이 없다고 판단되면 다른 분이 머지해주시면 감사하겠습니다..

[SP2/hotfix] 하이드레이션 에러 해결

---

src/views/BlogPage/components/BlogTab/style.ts

close #273 
블로그 모바일 탭 폰트 크기 css 가 누락되어 추가했습니다.
|전|후|
|--|--|
|<img width="313" alt="image" src="https://github.com/sopt-makers/sopt.org-frontend/assets/62867581/2276ad1c-cf77-4687-9813-8d585d188e5e">|<img width="311" alt="image" src="https://github.com/sopt-makers/sopt.org-frontend/assets/62867581/dba7015a-57e8-43eb-b927-32a3b425c9df">|

[SP2]블로그 모바일 탭 css 추가

---

src/components/common/Carousel/index.tsx
src/components/common/Carousel/style.ts
src/components/common/Select/index.tsx
src/components/common/Select/style.ts
src/lib/constants/project.ts
src/lib/types/universal.ts
src/views/BlogPage/components/BlogTab/index.tsx
src/views/BlogPage/components/BlogTab/style.ts
src/views/ProjectPage/ProjectPage.tsx
src/views/ProjectPage/components/RecentProjectList/Carousel/index.tsx
src/views/ProjectPage/components/project/ProjectCard/style.ts
src/views/ProjectPage/styles.ts

- close #274 
- 모바일 뷰에서 프로젝트 카드 서비스 이용 가능 및 창업 중 정보가 하단 오른쪽 자리(디자인 상 멤버 자리)에서 보여지고 있어서 왼쪽으로 이동
- 프로젝트 제목 한 줄 이상 초과시 ellipsie 처리 되도록 수정
- **_저희 프로젝트 탭 모바일 뷰가 굉장히 이상하게 보이고 있습니다..!_** (아래 이미지 참고) 모바일 뷰 width가 `360px`으로 되어 있었는데 [5304bd8](https://github.com/sopt-makers/sopt.org-frontend/pull/264/commits/5304bd830b9759554299441033abe15a7f694b4c) 커밋에서 `align-items: flex-start` 속성이 부여되면서 이렇게 된걸로 보입니다. 그래서 width `360px` 고정을 풀고 그냥 디자인대로 화면 사이즈에 맞게 너비가 넓어지게 해놨습니다. 
|수정 전|수정 후|
|--|--|
|![image](https://github.com/sopt-makers/sopt.org-frontend/assets/63948884/fc710ef1-c3a3-4747-97e9-8e614a28e9b4)|![image](https://github.com/sopt-makers/sopt.org-frontend/assets/63948884/86b20b84-84bc-4315-ba87-c28bfcf5fb60)|
- 추가적으로 위 사진을 보시면 아시겠지만 기존에는 디바이스가 모바일일 때만 화살표가 사라지고, PC 화면 사이즈가 `899px` 이하일 때는 화살표 및 블러가 …

[SP2] 프로젝트 탭 디자인 일부 수정

---

src/views/MainPage/components/Banner/RecruitButton/index.tsx
src/views/MainPage/components/Banner/RecruitButton/style.ts

- 모집 알림 신청 버튼에서 마우스 진입 시 생기는 동동이가 서서히 뜨도록 변경합니다
- 그 때 글씨도 살짝쿵 작아지도록 변경합니다.
https://github.com/sopt-makers/sopt.org-frontend/assets/48249505/856c408c-94cb-4e55-9772-b38322b8ae98
- 원래 동동이를 background-image로 띄웠으나, 그러면 서서히 밝아지는 효과가 적용되지 않아서
- before 속성으로 바꾸고 opacity에 transition을 주는 방식으로 변경하였습니다!!!!!!

[SP2] 메인페이지 모집알림신청 버튼 QA

---

src/components/Footer/MakersNForm/style.ts

close #305 
블로그 아티클에서 좋아요가 footer 위로 보이는 문제가 있었습니다. 
확인해보니 로컬 develop 브랜치에서는 footer z-index 가 99인데 공홈 실배포에서는 10으로 되어있더라고요?!
그래서 100으로 바꿔 둘다 같은 값으로 바뀌도록 해보았습니다!
|디벨롭|실제배포|
|--|--|
|<img width="502" alt="스크린샷 2023-12-01 오전 9 26 18" src="https://github.com/sopt-makers/sopt.org-frontend/assets/62867581/47110065-0b86-4584-bef2-0fa59c3ad9f4">|<img width="673" alt="스크린샷 2023-12-01 오전 9 26 47" src="https://github.com/sopt-makers/sopt.org-frontend/assets/62867581/48100b10-82d7-4848-b1ac-405de41464ee">|

[SP2]footer z-index 변경

---

src/views/MainPage/components/BottomLayout/style.ts

- close #329 
- 768px 부터는 좌우 하얀색 여백을 제거합니다.

[SP3] 모바일 메인 하단 백그라운드 제거

---

src/views/MainPage/components/Comment/Card/Desktop/index.tsx
src/views/MainPage/components/Comment/Card/Desktop/style.ts
src/views/MainPage/components/Comment/Cards/index.tsx
src/views/MainPage/components/Comment/style.ts

[SP3] 솝트어때요? 반응형 최최최종 수정

---

src/components/common/SEO/index.tsx

[SP0] OG 이미지 업데이트

---

src/pages/_app.tsx

기존 amplitude를 초기화하는 시점이 컴포넌트 바깥인데, 
이 경우 pages/project/[id] 에 있는 파일들이 구워질 때 에러가 발생합니다
정확한 원인은 모르지만, 일단 생명주기 안쪽으로 init하는 코드를 옮겨 문제를 해결하였습니다.
배포 전에 편할 때 develop으로 머지해 주세요!!

[SP-] 배포 시 일부 페이지가 amplitude 오류로 렌더되지 않는 오류 수정

---

.vscode/settings.json
pnpm-lock.yaml
src/assets/icons/ic_timer.svg
src/assets/icons/ic_view.svg
src/views/MainPage/MainPage.tsx
src/views/MainPage/components/Banner/RecruitButton/style.ts
src/views/MainPage/components/Banner/index.tsx
src/views/MainPage/components/PartConfig/index.tsx
src/views/MainPage/components/TopBanner/index.tsx
src/views/MainPage/components/TopBanner/style.ts
src/views/MainPage/hooks/useCheckTime.ts
src/views/MainPage/hooks/useFetch.ts
src/views/MainPage/hooks/usePost.ts

- closed #356 
https://github.com/sopt-makers/sopt.org-frontend/assets/81505421/ddb21040-3705-49d7-9810-10e689641626
- 34기 YB 지원하기 CTA -> 모집 시작하지 않은 /recruit 페이지로 이동 
- 상단 강조 배너 -> 모집 시작 시각부터 나타남 
- 데이터 패칭은 SP0 이후 리액트쿼리 적용 예정

[SP0] 34기 리크루팅 관련 메인페이지 업데이트 

---

src/hooks/useCheckTime.ts
src/lib/api/mock/about.ts
src/views/MainPage/components/TopBanner/style.ts
src/views/RecruitPage/components/ActivityReview/styles.ts
src/views/RecruitPage/components/Contact/index.tsx

누락된 QA 사항 
[fix: /recruit 문의하기 모바일 레이아웃 수정](https://github.com/sopt-makers/sopt.org-frontend/commit/d939d243c84865a2a3f5f40316798ab1d9aa61e6)

[SP0] 추가 QA -  /recruit 문의하기 모바일 레이아웃 수정

---

src/views/AboutPage/components/CoreValue/Item/style.ts
src/views/MainPage/components/Banner/RecruitButton/style.ts
src/views/MainPage/components/RecruitMessage/index.tsx
src/views/MainPage/components/TopBanner/style.ts
src/views/RecruitPage/components/ChapterInfo/index.tsx
src/views/RecruitPage/components/ChapterInfo/style.ts
src/views/RecruitPage/components/Schedule/index.tsx
src/views/RecruitPage/components/Schedule/style.ts
src/views/RecruitPage/components/common/Tabs/style.ts

[S0] 배포 후 QA 

---

src/components/Footer/MakersNForm/index.tsx
src/components/common/RoundButton/style.ts
src/views/ErrorPage/ErrorPage.tsx
src/views/ErrorPage/components/ErrorCode.tsx
src/views/ErrorPage/styles.ts

- closed #380 
- 문의하기 왈라폼 -> 카톡 링크로 변경
- 모바일뷰 폰트, 버튼 사이즈 다운
QA 사항 두가지 반영했습니다 
특히 모바일 브라우저의 자체 탭 때문에 view height가 달라져서
100vh를 의도했으나 **원치않는 스크롤**이 발생하는 경우가 많은데요 
이럴 때는 vh 단위를 dvh (dynamic view height)로 바꿔주면 사파리 등 탭 사이즈가 동적인 브라우저의 view height도 잘 대응해주게 됩니다

[SP0] 에러페이지 QA 반영 

---

src/components/Header/constants/menuTapList.ts

/recruit 페이지로 이동하던 링크를 저희가 만든 외부 지원서 링크로 이동하도록 수정했습니다 
> 사유 : OB 리크루팅 기간 동안은 /recruit 페이지에 현기수 브랜딩 및 정보가 반영될 수 없기 때문에, 해당 페이지를 거치지 않고 바로 지원서 페이지로 이동시키기 위함

[Fix] 지원하기 href 수정

---

src/pages/about.tsx
src/views/AboutPage/components/Member/Content/index.tsx
src/views/AboutPage/components/Member/Section/index.tsx
src/views/AboutPage/components/Member/Section/style.ts

close #415 
일단 기존에 `useGetMember` 쿼리 커스텀 훅으로 `members` 데이터를 받아왔었습니다.
```ts
const { data } = useGetMember();
const cardContent = useMemo(() => {
if (!isLoading)
return (data ? data.members : emptyMembers(6)).map(
({
id,
name,
position,
description,
currentProject,
imageSrc,
gmail,
linkedin,
github,
}) => (
<MemberCard
key={id}
name={name}
position={position}
description={description}
currentProject={currentProject}
imageSrc={imageSrc}
gmail={gmail}
linkedin={linkedin}
github={github}
/>
),
);
return (
<St.OvalSpinnerWrapper>
<OvalSpinner />
</St.OvalSpinnerWrapper>
);
}, [data, isLoading]);
```
사실 서버 컴포넌트의 이점을 살릴 수 있는 `NextJS`에서 `useQuery`를 통해 클라이언트 사이드 렌더링을 하는 것보다 기존의 `aboutInfo`를 `getStaticProps`를 통해 `prefetch` 하였던 것처럼 `memberInfo` 데이터 또한 사전에 생성하여 `props`로 건내주는 방식으로 리팩토링하였습니다.
```ts …
```

[Feat] memberInfo RQ에서 SSG fetching으로 수정

---

src/views/AboutPage/components/Record/Section/index.tsx
src/views/RecruitPage/components/NotificationSection/index.tsx

[Chore] 기수 수정

---

.github/workflows/ci.yml
src/pages/about.tsx
src/views/AboutPage/components/Banner/index.tsx
src/views/AboutPage/components/Banner/style.ts

- close #411 
소개페이지의 상단 배너 로딩 속도가 너무 느렸어요 
소개페이지의 가장 상단 콘텐츠이고 나름 메인 콘텐츠이기 때문에 개선이 시급한 친구라고 생각했습니다 ! 
(관련해서 아주 불편하다고 제보도 받았구요) 
해결책 고민하는 시간은 길었지만 결론적으로 작업한 코드는 정말 별거 없습니다 
- s3에 업로드되어있는 이미지 사이즈 수정 및 webp로 변환
- SSG 형식으로 불러오던 소개페이지 데이터를 ISR 형식으로 수정 (revalidate 간격 120초) 
- 상단 배너 element를 div 태그 -> next/image 컴포넌트로 수정 
레전드 쓰레기 LCP 발생 ! 
**LCP 3.5초 줄임**으로써 Performance 지수를 약 **20점 올릴 수 있었습니다** 🤙🏻
우선 아시다시피 소개페이지의 상단 배너는 저희가 로컬 이미지를 넣어주는 형태가 아니라 s3에 저장되어있는 이미지를 서버에서 받아와서 remote url을 src로 넣어주는 형태입니다 
그런데 이 이미지 상태가 심각했어요 
렌더되는 너비는 100vw여서 가장 커봤자 2000px보다 작을텐데 
저 불러오는 원본 이미지 너비는 무려 16400px........파일 사이즈는 3.8MB....  거의 100배에 달하게 큰 이미지를 받고 있더라구요  
백엔드 개발자분이 피그마에서 이미지를 추출해갈때 화질 저하를 막기 위해 4배로 뽑아가신게 원인이었어요 
이게 가장 치명적인 문제였기에 
이미지 다시 리사이징하고 또 최적화를 위해 형식도 webp로 변환해서 백엔드분께 파일 변경을 부탁드렸습니다 
이미지 리사이징은 너비 …

[Refactor] 소개페이지 상단 배너 로딩 속도 개선 

---

.github/workflows/ci.yml
src/views/MainPage/components/Banner/index.tsx
src/views/MainPage/components/RecruitMessage/index.tsx
src/views/MainPage/components/TopBanner/index.tsx

[Chore] 36기로 변경

---

src/lib/api/remote/about.ts
src/views/AboutPage/components/Record/Section/index.tsx

36기 모집 때는 dataPrev 이용해줘야 해서 주석처리해줬어요

chore: 활동 레코드 35기로 변경

---

pnpm-lock.yaml
src/components/common/Select/style.ts
src/views/BlogPage/components/BlogTab/style.ts

blog qa 반영했습니다. 
- 모바일 뷰에서 칩, 드롭다운 사이즈 작게 조정
디자인 상으로는 mds를 사용하고 있는데 공홈에서는 mds를 사용하지 않고 자체적으로 컴포넌트를 만들어서 사용하고 있었습니다.
그래서 mds를 설치하여 사용하려고 했는데 반응형 구현이 오히려 까다로워지는것 같아서 그냥 기존에 구현되어있던 컴포넌트에 반응형 처리를 해주었습니다.
- 모바일 뷰에서 “전체 활동” 옵션이 두줄로 보임 (활성화시 한 줄로 바뀜)
```ts
export const SelectItemContent = styled.p<{ isWide: boolean; breakPoint: string }>`
/* margin-right: ${({ isWide }) => isWide && '42px'}; */
```
드롭다운 item 글자수가 5글자 이상인 경우 오른쪽 마진이 생기는 구조로 구현되어있습니다.
그래서 "전체 활동" 의 경우 오른쪽 마진이 생겨서 뷰가 확장되는 에러가 있었습니다.
드롭다운이 있는 뷰를 다 살펴봤는데 `isWide` 속성이 왜 있는지 모르겠어서 일단 주석처리 해주어 문제를 해결해주었습니다.
혹시 `isWide`에 대해서 아는게 있으시면 알려주시면 감사하겠습니다..!

[Fix] sp1 blog qa 사항 반영
